//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Earth_In_Beats.WebService.TestApp.PlayerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceContextData", Namespace="http://schemas.datacontract.org/2004/07/Earth_In_Beats.WebService.WCF.Models")]
    [System.SerializableAttribute()]
    public partial class DeviceContextData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LongitudeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceData", Namespace="http://schemas.datacontract.org/2004/07/Earth_In_Beats.WebService.WCF.Models")]
    [System.SerializableAttribute()]
    public partial class DeviceData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Earth_In_Beats.WebService.TestApp.PlayerService.TrackData CurrentTrackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid PublicKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Earth_In_Beats.WebService.TestApp.PlayerService.TrackData CurrentTrack {
            get {
                return this.CurrentTrackField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentTrackField, value) != true)) {
                    this.CurrentTrackField = value;
                    this.RaisePropertyChanged("CurrentTrack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PublicKey {
            get {
                return this.PublicKeyField;
            }
            set {
                if ((this.PublicKeyField.Equals(value) != true)) {
                    this.PublicKeyField = value;
                    this.RaisePropertyChanged("PublicKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrackData", Namespace="http://schemas.datacontract.org/2004/07/Earth_In_Beats.WebService.WCF.Models")]
    [System.SerializableAttribute()]
    public partial class TrackData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArtistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Artist {
            get {
                return this.ArtistField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistField, value) != true)) {
                    this.ArtistField = value;
                    this.RaisePropertyChanged("Artist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PlayerService.PlayerService")]
    public interface PlayerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayerService/Connect", ReplyAction="http://tempuri.org/PlayerService/ConnectResponse")]
        Earth_In_Beats.WebService.TestApp.PlayerService.DeviceContextData Connect();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayerService/Connect", ReplyAction="http://tempuri.org/PlayerService/ConnectResponse")]
        System.Threading.Tasks.Task<Earth_In_Beats.WebService.TestApp.PlayerService.DeviceContextData> ConnectAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayerService/Disconnect", ReplyAction="http://tempuri.org/PlayerService/DisconnectResponse")]
        bool Disconnect(Earth_In_Beats.WebService.TestApp.PlayerService.DeviceContextData device);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayerService/Disconnect", ReplyAction="http://tempuri.org/PlayerService/DisconnectResponse")]
        System.Threading.Tasks.Task<bool> DisconnectAsync(Earth_In_Beats.WebService.TestApp.PlayerService.DeviceContextData device);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayerService/Get", ReplyAction="http://tempuri.org/PlayerService/GetResponse")]
        Earth_In_Beats.WebService.TestApp.PlayerService.DeviceData[] Get();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayerService/Get", ReplyAction="http://tempuri.org/PlayerService/GetResponse")]
        System.Threading.Tasks.Task<Earth_In_Beats.WebService.TestApp.PlayerService.DeviceData[]> GetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayerService/Update", ReplyAction="http://tempuri.org/PlayerService/UpdateResponse")]
        Earth_In_Beats.WebService.TestApp.PlayerService.DeviceContextData Update(Earth_In_Beats.WebService.TestApp.PlayerService.DeviceContextData device);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayerService/Update", ReplyAction="http://tempuri.org/PlayerService/UpdateResponse")]
        System.Threading.Tasks.Task<Earth_In_Beats.WebService.TestApp.PlayerService.DeviceContextData> UpdateAsync(Earth_In_Beats.WebService.TestApp.PlayerService.DeviceContextData device);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayerService/Play", ReplyAction="http://tempuri.org/PlayerService/PlayResponse")]
        bool Play(Earth_In_Beats.WebService.TestApp.PlayerService.DeviceContextData device, Earth_In_Beats.WebService.TestApp.PlayerService.TrackData track);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayerService/Play", ReplyAction="http://tempuri.org/PlayerService/PlayResponse")]
        System.Threading.Tasks.Task<bool> PlayAsync(Earth_In_Beats.WebService.TestApp.PlayerService.DeviceContextData device, Earth_In_Beats.WebService.TestApp.PlayerService.TrackData track);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayerService/Stop", ReplyAction="http://tempuri.org/PlayerService/StopResponse")]
        bool Stop(Earth_In_Beats.WebService.TestApp.PlayerService.DeviceContextData device);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayerService/Stop", ReplyAction="http://tempuri.org/PlayerService/StopResponse")]
        System.Threading.Tasks.Task<bool> StopAsync(Earth_In_Beats.WebService.TestApp.PlayerService.DeviceContextData device);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PlayerServiceChannel : Earth_In_Beats.WebService.TestApp.PlayerService.PlayerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlayerServiceClient : System.ServiceModel.ClientBase<Earth_In_Beats.WebService.TestApp.PlayerService.PlayerService>, Earth_In_Beats.WebService.TestApp.PlayerService.PlayerService {
        
        public PlayerServiceClient() {
        }
        
        public PlayerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlayerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Earth_In_Beats.WebService.TestApp.PlayerService.DeviceContextData Connect() {
            return base.Channel.Connect();
        }
        
        public System.Threading.Tasks.Task<Earth_In_Beats.WebService.TestApp.PlayerService.DeviceContextData> ConnectAsync() {
            return base.Channel.ConnectAsync();
        }
        
        public bool Disconnect(Earth_In_Beats.WebService.TestApp.PlayerService.DeviceContextData device) {
            return base.Channel.Disconnect(device);
        }
        
        public System.Threading.Tasks.Task<bool> DisconnectAsync(Earth_In_Beats.WebService.TestApp.PlayerService.DeviceContextData device) {
            return base.Channel.DisconnectAsync(device);
        }
        
        public Earth_In_Beats.WebService.TestApp.PlayerService.DeviceData[] Get() {
            return base.Channel.Get();
        }
        
        public System.Threading.Tasks.Task<Earth_In_Beats.WebService.TestApp.PlayerService.DeviceData[]> GetAsync() {
            return base.Channel.GetAsync();
        }
        
        public Earth_In_Beats.WebService.TestApp.PlayerService.DeviceContextData Update(Earth_In_Beats.WebService.TestApp.PlayerService.DeviceContextData device) {
            return base.Channel.Update(device);
        }
        
        public System.Threading.Tasks.Task<Earth_In_Beats.WebService.TestApp.PlayerService.DeviceContextData> UpdateAsync(Earth_In_Beats.WebService.TestApp.PlayerService.DeviceContextData device) {
            return base.Channel.UpdateAsync(device);
        }
        
        public bool Play(Earth_In_Beats.WebService.TestApp.PlayerService.DeviceContextData device, Earth_In_Beats.WebService.TestApp.PlayerService.TrackData track) {
            return base.Channel.Play(device, track);
        }
        
        public System.Threading.Tasks.Task<bool> PlayAsync(Earth_In_Beats.WebService.TestApp.PlayerService.DeviceContextData device, Earth_In_Beats.WebService.TestApp.PlayerService.TrackData track) {
            return base.Channel.PlayAsync(device, track);
        }
        
        public bool Stop(Earth_In_Beats.WebService.TestApp.PlayerService.DeviceContextData device) {
            return base.Channel.Stop(device);
        }
        
        public System.Threading.Tasks.Task<bool> StopAsync(Earth_In_Beats.WebService.TestApp.PlayerService.DeviceContextData device) {
            return base.Channel.StopAsync(device);
        }
    }
}
