//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Earth_In_Beats.WebService.Integration.PlayerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConnectRequest", Namespace="http://schemas.datacontract.org/2004/07/Earth_In_Beats.WebService.WCF.Contracts")]
    [System.SerializableAttribute()]
    public partial class ConnectRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceKey {
            get {
                return this.DeviceKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceKeyField, value) != true)) {
                    this.DeviceKeyField = value;
                    this.RaisePropertyChanged("DeviceKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/Earth_In_Beats.WebService.WCF.Contracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Earth_In_Beats.WebService.Integration.PlayerService.DisconnectResponce))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Earth_In_Beats.WebService.Integration.PlayerService.GetAllResponce))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Earth_In_Beats.WebService.Integration.PlayerService.UpdateResponce))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Earth_In_Beats.WebService.Integration.PlayerService.PlayResponce))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Earth_In_Beats.WebService.Integration.PlayerService.StopResponce))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Earth_In_Beats.WebService.Integration.PlayerService.ConnectResponce))]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DisconnectResponce", Namespace="http://schemas.datacontract.org/2004/07/Earth_In_Beats.WebService.WCF.Contracts")]
    [System.SerializableAttribute()]
    public partial class DisconnectResponce : Earth_In_Beats.WebService.Integration.PlayerService.Result {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAllResponce", Namespace="http://schemas.datacontract.org/2004/07/Earth_In_Beats.WebService.WCF.Contracts")]
    [System.SerializableAttribute()]
    public partial class GetAllResponce : Earth_In_Beats.WebService.Integration.PlayerService.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Earth_In_Beats.WebService.Integration.PlayerService.DeviceData[] DevicesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Earth_In_Beats.WebService.Integration.PlayerService.DeviceData[] Devices {
            get {
                return this.DevicesField;
            }
            set {
                if ((object.ReferenceEquals(this.DevicesField, value) != true)) {
                    this.DevicesField = value;
                    this.RaisePropertyChanged("Devices");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateResponce", Namespace="http://schemas.datacontract.org/2004/07/Earth_In_Beats.WebService.WCF.Contracts")]
    [System.SerializableAttribute()]
    public partial class UpdateResponce : Earth_In_Beats.WebService.Integration.PlayerService.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Earth_In_Beats.WebService.Integration.PlayerService.DeviceContextData DeviceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Earth_In_Beats.WebService.Integration.PlayerService.DeviceContextData Device {
            get {
                return this.DeviceField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceField, value) != true)) {
                    this.DeviceField = value;
                    this.RaisePropertyChanged("Device");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayResponce", Namespace="http://schemas.datacontract.org/2004/07/Earth_In_Beats.WebService.WCF.Contracts")]
    [System.SerializableAttribute()]
    public partial class PlayResponce : Earth_In_Beats.WebService.Integration.PlayerService.Result {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StopResponce", Namespace="http://schemas.datacontract.org/2004/07/Earth_In_Beats.WebService.WCF.Contracts")]
    [System.SerializableAttribute()]
    public partial class StopResponce : Earth_In_Beats.WebService.Integration.PlayerService.Result {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConnectResponce", Namespace="http://schemas.datacontract.org/2004/07/Earth_In_Beats.WebService.WCF.Contracts")]
    [System.SerializableAttribute()]
    public partial class ConnectResponce : Earth_In_Beats.WebService.Integration.PlayerService.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceData", Namespace="http://schemas.datacontract.org/2004/07/Earth_In_Beats.WebService.WCF.Models")]
    [System.SerializableAttribute()]
    public partial class DeviceData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Earth_In_Beats.WebService.Integration.PlayerService.TrackData CurrentTrackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid PublicKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Earth_In_Beats.WebService.Integration.PlayerService.TrackData CurrentTrack {
            get {
                return this.CurrentTrackField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentTrackField, value) != true)) {
                    this.CurrentTrackField = value;
                    this.RaisePropertyChanged("CurrentTrack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PublicKey {
            get {
                return this.PublicKeyField;
            }
            set {
                if ((this.PublicKeyField.Equals(value) != true)) {
                    this.PublicKeyField = value;
                    this.RaisePropertyChanged("PublicKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrackData", Namespace="http://schemas.datacontract.org/2004/07/Earth_In_Beats.WebService.WCF.Models")]
    [System.SerializableAttribute()]
    public partial class TrackData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArtistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Artist {
            get {
                return this.ArtistField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistField, value) != true)) {
                    this.ArtistField = value;
                    this.RaisePropertyChanged("Artist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceContextData", Namespace="http://schemas.datacontract.org/2004/07/Earth_In_Beats.WebService.WCF.Models")]
    [System.SerializableAttribute()]
    public partial class DeviceContextData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LongitudeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DisconnectRequest", Namespace="http://schemas.datacontract.org/2004/07/Earth_In_Beats.WebService.WCF.Contracts")]
    [System.SerializableAttribute()]
    public partial class DisconnectRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAllRequest", Namespace="http://schemas.datacontract.org/2004/07/Earth_In_Beats.WebService.WCF.Contracts")]
    [System.SerializableAttribute()]
    public partial class GetAllRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateRequst", Namespace="http://schemas.datacontract.org/2004/07/Earth_In_Beats.WebService.WCF.Contracts")]
    [System.SerializableAttribute()]
    public partial class UpdateRequst : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LongitudeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayRequest", Namespace="http://schemas.datacontract.org/2004/07/Earth_In_Beats.WebService.WCF.Contracts")]
    [System.SerializableAttribute()]
    public partial class PlayRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArtistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Artist {
            get {
                return this.ArtistField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistField, value) != true)) {
                    this.ArtistField = value;
                    this.RaisePropertyChanged("Artist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StopRequest", Namespace="http://schemas.datacontract.org/2004/07/Earth_In_Beats.WebService.WCF.Contracts")]
    [System.SerializableAttribute()]
    public partial class StopRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PlayerService.PlayerService")]
    public interface PlayerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayerService/Connect", ReplyAction="http://tempuri.org/PlayerService/ConnectResponse")]
        Earth_In_Beats.WebService.Integration.PlayerService.ConnectResponce Connect(Earth_In_Beats.WebService.Integration.PlayerService.ConnectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayerService/Connect", ReplyAction="http://tempuri.org/PlayerService/ConnectResponse")]
        System.Threading.Tasks.Task<Earth_In_Beats.WebService.Integration.PlayerService.ConnectResponce> ConnectAsync(Earth_In_Beats.WebService.Integration.PlayerService.ConnectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayerService/Disconnect", ReplyAction="http://tempuri.org/PlayerService/DisconnectResponse")]
        Earth_In_Beats.WebService.Integration.PlayerService.DisconnectResponce Disconnect(Earth_In_Beats.WebService.Integration.PlayerService.DisconnectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayerService/Disconnect", ReplyAction="http://tempuri.org/PlayerService/DisconnectResponse")]
        System.Threading.Tasks.Task<Earth_In_Beats.WebService.Integration.PlayerService.DisconnectResponce> DisconnectAsync(Earth_In_Beats.WebService.Integration.PlayerService.DisconnectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayerService/Get", ReplyAction="http://tempuri.org/PlayerService/GetResponse")]
        Earth_In_Beats.WebService.Integration.PlayerService.GetAllResponce Get(Earth_In_Beats.WebService.Integration.PlayerService.GetAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayerService/Get", ReplyAction="http://tempuri.org/PlayerService/GetResponse")]
        System.Threading.Tasks.Task<Earth_In_Beats.WebService.Integration.PlayerService.GetAllResponce> GetAsync(Earth_In_Beats.WebService.Integration.PlayerService.GetAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayerService/Update", ReplyAction="http://tempuri.org/PlayerService/UpdateResponse")]
        Earth_In_Beats.WebService.Integration.PlayerService.UpdateResponce Update(Earth_In_Beats.WebService.Integration.PlayerService.UpdateRequst request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayerService/Update", ReplyAction="http://tempuri.org/PlayerService/UpdateResponse")]
        System.Threading.Tasks.Task<Earth_In_Beats.WebService.Integration.PlayerService.UpdateResponce> UpdateAsync(Earth_In_Beats.WebService.Integration.PlayerService.UpdateRequst request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayerService/Play", ReplyAction="http://tempuri.org/PlayerService/PlayResponse")]
        Earth_In_Beats.WebService.Integration.PlayerService.PlayResponce Play(Earth_In_Beats.WebService.Integration.PlayerService.PlayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayerService/Play", ReplyAction="http://tempuri.org/PlayerService/PlayResponse")]
        System.Threading.Tasks.Task<Earth_In_Beats.WebService.Integration.PlayerService.PlayResponce> PlayAsync(Earth_In_Beats.WebService.Integration.PlayerService.PlayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayerService/Stop", ReplyAction="http://tempuri.org/PlayerService/StopResponse")]
        Earth_In_Beats.WebService.Integration.PlayerService.StopResponce Stop(Earth_In_Beats.WebService.Integration.PlayerService.StopRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayerService/Stop", ReplyAction="http://tempuri.org/PlayerService/StopResponse")]
        System.Threading.Tasks.Task<Earth_In_Beats.WebService.Integration.PlayerService.StopResponce> StopAsync(Earth_In_Beats.WebService.Integration.PlayerService.StopRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PlayerServiceChannel : Earth_In_Beats.WebService.Integration.PlayerService.PlayerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlayerServiceClient : System.ServiceModel.ClientBase<Earth_In_Beats.WebService.Integration.PlayerService.PlayerService>, Earth_In_Beats.WebService.Integration.PlayerService.PlayerService {
        
        public PlayerServiceClient() {
        }
        
        public PlayerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlayerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Earth_In_Beats.WebService.Integration.PlayerService.ConnectResponce Connect(Earth_In_Beats.WebService.Integration.PlayerService.ConnectRequest request) {
            return base.Channel.Connect(request);
        }
        
        public System.Threading.Tasks.Task<Earth_In_Beats.WebService.Integration.PlayerService.ConnectResponce> ConnectAsync(Earth_In_Beats.WebService.Integration.PlayerService.ConnectRequest request) {
            return base.Channel.ConnectAsync(request);
        }
        
        public Earth_In_Beats.WebService.Integration.PlayerService.DisconnectResponce Disconnect(Earth_In_Beats.WebService.Integration.PlayerService.DisconnectRequest request) {
            return base.Channel.Disconnect(request);
        }
        
        public System.Threading.Tasks.Task<Earth_In_Beats.WebService.Integration.PlayerService.DisconnectResponce> DisconnectAsync(Earth_In_Beats.WebService.Integration.PlayerService.DisconnectRequest request) {
            return base.Channel.DisconnectAsync(request);
        }
        
        public Earth_In_Beats.WebService.Integration.PlayerService.GetAllResponce Get(Earth_In_Beats.WebService.Integration.PlayerService.GetAllRequest request) {
            return base.Channel.Get(request);
        }
        
        public System.Threading.Tasks.Task<Earth_In_Beats.WebService.Integration.PlayerService.GetAllResponce> GetAsync(Earth_In_Beats.WebService.Integration.PlayerService.GetAllRequest request) {
            return base.Channel.GetAsync(request);
        }
        
        public Earth_In_Beats.WebService.Integration.PlayerService.UpdateResponce Update(Earth_In_Beats.WebService.Integration.PlayerService.UpdateRequst request) {
            return base.Channel.Update(request);
        }
        
        public System.Threading.Tasks.Task<Earth_In_Beats.WebService.Integration.PlayerService.UpdateResponce> UpdateAsync(Earth_In_Beats.WebService.Integration.PlayerService.UpdateRequst request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public Earth_In_Beats.WebService.Integration.PlayerService.PlayResponce Play(Earth_In_Beats.WebService.Integration.PlayerService.PlayRequest request) {
            return base.Channel.Play(request);
        }
        
        public System.Threading.Tasks.Task<Earth_In_Beats.WebService.Integration.PlayerService.PlayResponce> PlayAsync(Earth_In_Beats.WebService.Integration.PlayerService.PlayRequest request) {
            return base.Channel.PlayAsync(request);
        }
        
        public Earth_In_Beats.WebService.Integration.PlayerService.StopResponce Stop(Earth_In_Beats.WebService.Integration.PlayerService.StopRequest request) {
            return base.Channel.Stop(request);
        }
        
        public System.Threading.Tasks.Task<Earth_In_Beats.WebService.Integration.PlayerService.StopResponce> StopAsync(Earth_In_Beats.WebService.Integration.PlayerService.StopRequest request) {
            return base.Channel.StopAsync(request);
        }
    }
}
